version: '3.8'

services:
  wordpress:
    build: requirements/wordpress
    image: wordpress_image
    env_file:
      - .env
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    build: requirements/nginx
    image: nginx_image
    env_file:
      - .env
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

networks:
  inception:

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eates/data/wordpress
